---
spring:
  application:
    name: spring-cloud-eureka-producer
  profiles: singleton

server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8003/eureka/

