spring:
  application:
    name: spring-cloud-eurka-consumer

server:
  port: 8002

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/



