---
spring:
  application:
    name: spring-cloud-eureka-consumer
  profiles: singleton

server:
  port: 8002

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8003/eureka/



