server:
  port: 8002

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

spring:
  application:
    name: eurka-client

